export const ADDINGREDIENT='ADDINGREDIENT'
export const REMOVEINGREDIENT='REMOVEINGREDIENT'
export const SETINGREDIENTS='SETINGREDIENTS'
export const FETCHINGREDIENTSFAILED='FETCHINGREDIENTSFAILED'

export const PURCHASEBURGERSUCCESS='PURCHASEBURGERSUCCESS'
export const PURCHASEBURGERFAIL='PURCHASEBURGERFAIL '
export const PURCHASEBURGERSTART='PURCHASEBURGERSTART'
export const PURCHASE_INIT='PURCHASE_INIT'

export const FETCHORDERSTART='FETCHORDERSSTART'
export const FETCHORDERSUCCESS='FETCHORDERSSUCCESS'
export const FETCHORDERFAIL='FETCHORDERFAIL'

export const AUTHSTART='AUTHSTART'
export const AUTHSUCCESS='AUTHSUCCESS'
export const AUTHFAIL='AUTHFAIL'
export const AUTHLOGOUT='AUTHLOGOUT '

export const SETAUTHREDIRECTPATH='SETAUTHREDIRECTPATH'
